### PR TITLE
members data fetch from backend api

### PR DESCRIPTION
**Pull request by kirtankp**
@PRATHAM1ST all details is fetched but there is some issue coming in profile_url (members profile picture) fetching

### CODE REVIEW

**Comment by PRATHAM1ST** [comment]
can you give me more details on this??

profile url is an btw image

**Comment by PRATHAM1ST** [comment]
image

great work @kirtankp

**Comment by kirtankp** [comment]
> can you give me more details on this??
> 
> profile url is an image
 
> ya got it but there was some issue pics were not coming but now it is solved.
>
> and which other details needed that you provide me, so i make change

**Comment by PRATHAM1ST** [comment]
@kirtankp Yeah a tip, whenever you start doing something check if there is any pull that you have to take from the branch.

I have made some changes to the code in frontend so, take the pull request and I have also renamed the ~profile_url~

```
profile_url -> profile_pic_url
```

> > ya got it but there was some issue pics were not coming but now it is solved.
> > and which other details needed that you provide me, so i make change

**Comment by kirtankp** [comment]
> @kirtankp Yeah a tip, whenever you start doing something check if there is any pull that you have to take from the branch.
> 
> I have made some changes to the code in frontend so, take the pull request and I have also renamed the ~profile_url~
> 
> ```
> profile_url -> profile_pic_url
> ```
> 
>
Ohk got it.. 👍🏻

**Pull request closed without merging**
